'''
Created on Aug 6, 2014

@author: sush
'''
ID_KEY = '_id'
CLASS_NODE_COLLECTION = 'classNodes'
NAME_NODE_COLLECTION = 'nameNodes'
PROPERTY_NODE_COLLECTION = 'propNodes'
OBJECT_NODE_COLLECTION = 'objNodes'
IS_PRIVATE_KEY = 'isPrivate'
VIEWERS_KEY = 'viewers'
DOMAIN_KEY = 'domain'
USER_NAME_KEY = 'username'
RANGE_KEY = 'range'
NAME_KEY = 'name'
OWNER_KEY = 'owner'
NAME_NODE_ID_KEY = 'nameNodeId'
PROP_NAME_KEY = 'propName'
CLASS_NAME_KEY = 'className'
OBJECT_NAME_KEY = 'objectName'
UPDATED_EXISTING_KEY = 'updatedExisting'
USER_SECRET_KEY = 'secret'
CLASS_STORE_TYPE = 'ClassStore'
PROP_STORE_TYPE = 'PropertyStore'