'''
Created on Aug 6, 2014

@author: sushant pradhan
'''
ID_KEY = '_id'
FORM_NODE_COLLECTION = 'formNodes'
VERB_NODE_COLLECTION = 'verbNodes'
CLASS_NODE_COLLECTION = 'classNodes'
OBJECT_NODE_COLLECTION = 'objNodes'
NAME_NODE_COLLECTION = 'nameNodes'
PROPERTY_NODE_COLLECTION = 'propNodes'
IS_PRIVATE_KEY = 'isPrivate'
#store keys
VIEWERS_KEY = 'viewers'
DOMAIN_KEY = 'domain'
FORM_KEY = 'form'
VERB_KEY = 'verb'
USER_NAME_KEY = 'username'
RANGE_KEY = 'range'
NAME_KEY = 'name'
OWNER_KEY = 'owner'
NAME_LENGTH_KEY = 'length'
NAME_NODE_ID_KEY = 'nameNodeId'
#name keys
PROP_NAME_KEY = 'propName'
CLASS_NAME_KEY = 'className'
FORM_NAME_KEY = 'formName'
OBJECT_NAME_KEY = 'objectName'
VERB_NAME_KEY = 'verbName'

UPDATED_EXISTING_KEY = 'updatedExisting'
USER_SECRET_KEY = 'secret'
FORM_FIELD_QUERY_CLASS = 'queryClass'
FORM_FIELD_CARDINALITY = 'cardinality'
FORM_PUBLIC_FIELD = 'publicFields'

#Store Types
CLASS_STORE_TYPE = 'ClassStore'
PROP_STORE_TYPE = 'PropertyStore'
VERB_STORE_TYPE = 'VerbStore'
FORM_STORE_TYPE = 'FormStore'
OBJECT_STORE_TYPE = 'ObjectStore'

PROP_VALUE_KEY = 'val'
OBJECT_TYPE_LINK = 'type'
STRING_POSITION1_LINK = 'pos_1'
STRING_POSITION2_LINK = 'pos_2'
STRING_POSITION3_LINK = 'pos_3'
#store names
PUBLIC_FORM_STORE = 'publicFormStore'
PUBLIC_VERB_STORE = 'publicVerbStore'
PUBLIC_PROP_STORE = 'publicPropStore'
PUBLIC_CLASS_STORE = 'publicClassStore'
PRIVATE_PROP_STORE = 'privatePropStore'
PRIVATE_CLASS_STORE = 'privateClassStore'
PRIVATE_FORM_STORE = 'privateFormStore'